[data]
UD_BASE="/data/UD-PUD"
BELEBELE_BASE="/data/belebele"

[languages]

[data.lang.english]
iso639="eng_Latn"
handle="UD_English-PUD/en_pud-ud-test.conllu"

[data.lang.turkish]
iso639="tur_Latn"
handle="UD_Turkish-PUD/tr_pud-tr-test.conllu"

[data.lang.chinese]
iso639="zho_Hans"
handle="UD_Chinese-PUD/zh_pud-ud-test.conllu"

[eval]
# (model, tokenizer) tuples
models=[
    ["toksuite/google-byt5-small", "google/byt5-small"],
    ["toksuite/facebook-xglm-564M", "facebook/xglm-564M"],
    ["toksuite/bigscience-bloom", "bigscience/bloom"],
    ["toksuite/gpt2", "gpt2"],
]
