[dir]
ud_base="$MIMER_DIR/tokefx-dev/data/UD_PUD/"
belebele_base="$MIMER_DIR/tokefx-dev/data/belebele/"
out="$MIMER_DIR/tokefx-dev/out"

[lang]

[lang.english]
iso639="eng_Latn"
pud-conllu="UD_English-PUD/en_pud-ud-test.conllu"

[lang.turkish]
iso639="tur_Latn"
pud-conllu="UD_Turkish-PUD/tr_pud-tr-test.conllu"

[lang.chinese]
iso639="zho_Hans"
pud-conllu="UD_Chinese-PUD/zh_pud-ud-test.conllu"

[eval]
# (model, tokenizer) tuples
models=[
    ["toksuite/bigscience-bloom", "bigscience/bloom"],
    ["toksuite/google-byt5-small", "google/byt5-small"],
    ["toksuite/facebook-xglm-564M", "facebook/xglm-564M"],
    ["toksuite/gpt2", "gpt2"],
]
device="cuda"
add_special_tokens=false
