#!/usr/bin/env python3
import argparse
from pathlib import Path
import subprocess
import shutil

from tokefx.utils import log, load_config

parser = argparse.ArgumentParser()
parser.add_argument(
    "cfg",
    type=Path,
    help="path to config file",
)
parser.add_argument(
    "--overwrite",
    action="store_true",
    help="delete output dir before run",
)
parser.add_argument(
    "--ablation_map_type",
    choices=["lahis", "attention_mass"],
    default="attention_mass",
    help="which method to derive ablation map from. defaults to %(default)s.",
)
parser.add_argument(
    "--in_boundary_mode",
    choices=["all", "embed"],
    default="all",
    help="which in_boundary mode to use. defaults to %(default)s.",
)
args = parser.parse_args()
CFG = load_config(args.cfg)
OUT_DIR = Path(CFG["dir"]["out"])

if args.overwrite:
    shutil.rmtree(OUT_DIR)
if OUT_DIR.exists():
    raise FileExistsError(
        f"output directory {OUT_DIR=} exists but --overwrite is not specified"
    )
OUT_DIR.mkdir(parents=True)
log("STARTING COMPLETE RUN")
log(CFG)
del CFG

log("CALCULATING ATTENTION HEAD ACTIVATION PATTERNS")
scrmap = {"lahis": "scripts/lahis.py", "attention_mass": "scripts/attention.py"}
script = scrmap.get(args.ablation_map_type, None)
if script is None:
    raise ValueError("unknown ablation_map_type")
subprocess.run(
    ["python3", script, args.cfg, "--in_boundary_mode", args.in_boundary_mode],
    check=True,
)
log("RUNNING ABLATION EXPERIMENTS")
subprocess.run(
    [
        "python3",
        "scripts/patchscopes.py",
        args.cfg,
        "--in_boundary_mode",
        args.in_boundary_mode,
        "--ablation_map_type",
        args.ablation_map_type,
    ],
    check=True,
)
log("FINISHED COMPLETE RUN")
